Fix bug in .gitignore

diff --git a/create-project b/create-project
--- a/create-project
+++ b/create-project
@@ -1,7 +1,31 @@
 #/bin/bash
+projectName=""
+execName=""
 
-cp -R base $1
-sed -i "s/<operacao>/$2/g" $1/script.c
-sed -i "s/<operacao>/$2/g" $1/makefile
-echo "!$1" >> .gitignore
-mv $1/script.c $1/$2.c
+while getopts ":p:e:" opt; do
+  case $opt in
+    e)
+      # -e execName: captura o nome do executavel
+      execName=$OPTARG
+      ;;
+    p)
+      # -p projectName: captura o nome do projeto
+      projectName=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+
+cp -R _base $projectName
+sed -i "s/<operacao>/$execName/g" $projectName/script.c
+sed -i "s/<operacao>/$execName/g" $projectName/makefile
+echo "!$projectName" >> .gitignore
+mv $projectName/script.c $projectName/$execName.c
